### ISSUE TITLE
Unable to build with angular-cli 1.0.0

### ISSUE THREAD

**Issue by danielcheng825** [gmazzamuto/ng2-google-charts#10]
Since the angular-cli 1.0.0 release, the project is unable to build using `ng build --prod`.
It gives the error message

    ERROR in .../node_modules/ng2-google-charts/google-chart/google-chart.component.ngfactory.ts (38,20): Property 'data' is private and only accessible within class 'GoogleChartComponent'.

**Comment by gmazzamuto** [comment]
Unfortunately I am not able to reproduce your problem, it works for me even with angular-cli 1.0.0

**Comment by danielcheng825** [comment]
Sorry, it works now. Must be some npm dependency problem. Thanks.
