### ISSUE TITLE
clicking org chart?

### ISSUE THREAD

**Issue by Dj-jom2x** [gmazzamuto/ng2-google-charts#100]
if i wanted to click it and return what i click how to do that? also how can i add a material button angular inside?

**Comment by gmazzamuto** [comment]
```html
<google-chart [data]="orgChart" (chartSelect)="select($event)"></google-chart>
```

Please refer to the [demo](https://www.devrandom.it/software/ng2-google-charts/demo/) for a complete example

**Comment by Dj-jom2x** [comment]
hmm this is not related  to my question but 

``   dataTable: [
      ['Name',   'Manager', 'Tooltip'],
      ['Alice', '', ''],
      ['Bob', 'Alice', 'Bob Sponge'],
      ['Carol', 'Alice', ''],
      ['Bob1', 'Bob', 'Bob Sponge'],
      ['+', 'Bob', ''],
      ['Carol2', 'Carol', 'Bob Sponge'],
      ['++', 'Carol', '']
    ],``

i cant insert duplicate .. you see the + and ++ are different because if i make that + carol with ++ it wont render..

**Comment by gmazzamuto** [comment]
what you want to do doesn't work with google charts:
https://jsfiddle.net/7bdwv86m/1/

this is not a problem related to this package
