### ISSUE TITLE
Cannot Find Module "GoogleChartInterface"

### ISSUE THREAD

**Issue by kocagozcem** [gmazzamuto/ng2-google-charts#102]
Hey, When i try to import GoogleChartInterface  like these;
`
import { GoogleChartInterface } from 'ng2-google-charts/google-charts-interfaces';`

i got red underline on file name. I could create charts by define any to my chart data object. But i need to use advanced usage to use draw() function. I would appreciate if you help.

**Comment by gmazzamuto** [comment]
Seems like a configuration issue in your project, please clone this repository and follow the implementation of the demo app to see how the project needs to be configured and the module imported

**Comment by desarrollojjcorp** [comment]
Can you resolve this issue, whats wrong with?
