### ISSUE TITLE
3D support for Bar/Column chart?

### ISSUE THREAD

**Issue by MathavanN** [gmazzamuto/ng2-google-charts#112]
Like Pie chart got option for 3D, does this package support for Bar/Column chart

**Comment by gmazzamuto** [comment]
This package is a wrapper for the [Google Charts](https://developers.google.com/chart) library. If it's not supported by the underlying library (which it seems to be the case for Bar and Column charts), then it's not supported by this package.

You can have a 3D Pie Chart though:

```ts
  public pieChart: GoogleChartInterface = {
    chartType: 'PieChart',
    dataTable: [
      ['Task', 'Hours per Day'],
      ['Work',     11],
      ['Eat',      2],
      ['Commute',  2],
      ['Watch TV', 2],
      ['Sleep',    7]
    ],
    options: {
      title: 'Tasks',
      slices: {
        0: {offset: 0.3},
        1: {offset: 0.2}
      },
      is3D: true,
    }
  };
```
