### ISSUE TITLE
chartSelect not emit event when same bar clicked from timeline chart.

### ISSUE THREAD

**Issue by Digoro** [gmazzamuto/ng2-google-charts#113]
before ask for problem, thank you ng2-google-charts.

when i click same timeline bar, chartSelect emitter is not emit event.

how can i try? or can i access original google chart api like 'select'?

**Comment by gmazzamuto** [comment]
It appears that the underlying Google Charts library does not emit the event, as you can see in [this fiddle](https://jsfiddle.net/rnmodxc1/): try clicking on a timeline bar and then again on the same bar.

Anyways I've modified the [demo](https://www.devrandom.it/software/ng2-google-charts/demo/) with an example that shows how you can programmatically clear the selection on a timeline chart.
