### ISSUE TITLE
Breaks universal ssr when module gets loaded

### ISSUE THREAD

**Issue by bkielczewski** [gmazzamuto/ng2-google-charts#116]
In bundles/ng2-google-charts.umd.js you have:

    (function webpackUniversalModuleDefinition(root, factory) {
	    if(typeof exports === 'object' && typeof module === 'object')
		    module.exports = factory(require("@angular/core"));
    	else if(typeof define === 'function' && define.amd)
	    	define(["@angular/core"], factory);
    	else if(typeof exports === 'object')
    		exports["ng2-google-charts.umd"] = factory(require("@angular/core"));
    	else
     		root["ng2-google-charts.umd"] = factory(root["@angular/core"]);
    })(window, function(__WEBPACK_EXTERNAL_MODULE__0__) {

Obviously resulting in `ReferenceError: window is not defined` when Ng2GoogleChartsModule is loaded server-side.

**Comment by bkielczewski** [comment]
I've noticed this comes from ngm-cli you're using for your build. My advice would be to consider switching to [Angular CLI library project](https://angular.io/guide/creating-libraries) for your build. The bundles it generates don't have window object passed if it's not used and in general it's a 'more Angular way' of achieving the same without relying on other 3rd party projects.

**Comment by gmazzamuto** [comment]
I have already switched just after I saw the issue, I'll release a new version soon

**Comment by bkielczewski** [comment]
Great, thanks!
