### ISSUE TITLE
draw() method on the viewchild. How to use it ?

### ISSUE THREAD

**Issue by adibro500** [gmazzamuto/ng2-google-charts#119]
How to use draw() method on the viewchild ? Please help. Not able to redraw or draw. I am using angular 9.

**Comment by gmazzamuto** [comment]
Please see [here](https://github.com/gmazzamuto/ng2-google-charts/blob/0c6e73b09de42ef5bf1f7bcf383ad966ec69480e/src/app/charts-gallery/charts-gallery.component.ts#L607).
