### ISSUE TITLE
ng2-google-charts not working

### ISSUE THREAD

**Issue by souravmondal93** [gmazzamuto/ng2-google-charts#12]
I followed the instruction mentioned in readme file. But, still I am not able to integrate the charts successfully with my project.

1. Ran `npm i --save ng2-google-charts`.
2. Imported the `Ng2GoogleChartsModule` in your `app.module.ts`.
3. Used the same markup and data in `.ts` file as shown in example.

Following is the error that I am getting.

```javascript
Can't bind to 'data' since it isn't a known property of 'google-chart'.
1. If 'google-chart' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'google-chart' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        <div class="col-sm-12">
            <h2>Gaugh Chart</h2>
            <google-chart [ERROR ->][data]="pieChartOptions"></google-chart>
        </div>
    </div>
"): SummaryComponent@18:26
'google-chart' is not a known element:
1. If 'google-chart' is an Angular component, then verify that it is part of this module.
2. If 'google-chart' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
        <div class="col-sm-12">
            <h2>Gaugh Chart</h2>
            [ERROR ->]<google-chart [data]="pieChartOptions"></google-chart>
        </div>
    </div>
"): SummaryComponent@18:12 ; Zone: <root> ; Task: Promise.then ; Value: 
```

Also, thanks for creating this awesome project. :)

**Comment by viwell** [comment]
Did you import `Ng2GoogleChartsModule` in your `app.module.ts` like the described example in usage section?
```typescript
import { Ng2GoogleChartsModule } from 'ng2-google-charts';

@NgModule({
  ...
  imports: [
    ...
    Ng2GoogleChartsModule,
  ],
})
export class AppModule { }
```

Note the `Ng2GoogleChartsModule` inside `@NgModule`

**Comment by souravmondal93** [comment]
@viwell Yeah, I put it inside `imports` of `@NgModule`.

**Comment by gmazzamuto** [comment]
I can't tell what the problem is here. I just tried starting a new project from scratch with the latest angular-cli 1.0.0 and everything works:
```
ng new myproject
cd myproject
npm i --save ng2-google-charts
```
and then I followed the instructions in [README.md](../blob/master/README.md).

**Comment by souravmondal93** [comment]
Thanks @gmazzamuto for the testing. I would like to ask one more thing. Suppose, if I am using `@NgModule` apart from the root module, then how should I import it? Do we need to do anything in the component `.ts` file apart from setting the chart options, chart data and markup?

**Comment by souravmondal93** [comment]
I made the charts working. I had to import it in barrel module instead of root module. Thanks @viwell  and @gmazzamuto for your help. I am closing the issue.

**Comment by sunilbehera91** [comment]
Failed: Template parse errors:
Can't bind to 'chartData' since it isn't a known property of 'div'. (" <div class="col-sm-12">
                
                <div class="mt-3 minH250" id="line_chart" [ERROR ->][chartData]="avgContributionRateChart.data" [chartOptions]="avgContributionRateChart.options" chartTy"): ng:///DynamicTestModule/AverageContributionRateComponent.html@76:58
Can't bind to 'chartOptions' since it isn't a known property of 'div'. ("              <div class="mt-3 minH250" id="line_chart" [chartData]="avgContributionRateChart.data" [ERROR ->][chartOptions]="avgContributionRateChart.options" chartType="LineChart" GoogleChart></div>
          "): ng:///DynamicTestModule/AverageContributionRateComponent.html@76:102
Can't bind to 'chartData' since it isn't a known property of 'div'. (""row">
            <div class="col-sm-12">
                <div class="mt-3 minH250" id="bar_chart" [ERROR ->][chartData]="activeLoansChart.data" [chartOptions]="activeLoansChart.options" chartType="ColumnChart""): ng:///DynamicTestModule/AverageContributionRateComponent.html@85:57
Can't bind to 'chartOptions' since it isn't a known property of 'div'. ("m-12">
                <div class="mt-3 minH250" id="bar_chart" [chartData]="activeLoansChart.data" [ERROR ->][chartOptions]="activeLoansChart.options" chartType="ColumnChart"
                    GoogleChart></d"): ng:///DynamicTestModule/AverageContributionRateComponent.html@85:93

**Comment by sunilbehera91** [comment]
i have in the error that I am getting.the error , how to solve the error ?
