### ISSUE TITLE
how to convert google chart in pdf format

### ISSUE THREAD

**Issue by ajinkyabapat1** [gmazzamuto/ng2-google-charts#122]
I am able to get google chart but i need to convert that in pdf format on button click .How to do this ?

**Comment by gmazzamuto** [comment]
Maybe you could get the PNG of the chart as shown in the demo, then use it with some library for PDF creation more or less like this:
```js
var imgData = this.columnChart.component.wrapper.getChart().getImageURI();
  
// Generate PDF
var doc = new jsPDF('p', 'pt', 'a4');
doc.addImage(imgData, 'PNG', 40, 40, 75, 75);
doc.save('test.pdf');
```
