### ISSUE TITLE
How to use mapsApiKey?

### ISSUE THREAD

**Issue by arthurangelo** [gmazzamuto/ng2-google-charts#126]
Hello, I'm generating the graph like this:

{
      chartType: 'GeoChart',
      dataTable: [['Estado','Total'],'BR-AC',1]
      options: {
                  region: 'BR', // regiao do brazil
                  resolution: 'provinces',
                  colorAxis: { colors: ['#FFD36B', '#FABB5C', '#F5A34C', '#F08B3D', '#EC742E', '#E75C1F', '#E2440F', '#DD2C00'] }, // cor 
                   do grafico vai de laranja para vermelho
                  backgroundColor: '#81d4fa', // cor do mar em volta do continente
                 datalessRegionColor: '#c6dabf', // cor dos paises em volta do brasil
                 defaultColor: '#f5f5f5',
                  legend: 'none',
                 geochartVersion: 11
                },
      mapsApiKey: 'xxx',

   };

What is the correct way to send mapsApiKey?
I have the following error: eocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account

**Comment by gmazzamuto** [comment]
Please see line 4 in the first block of code in this page:
https://www.devrandom.it/software/ng2-google-charts/additional-documentation/usage.html
