### ISSUE TITLE
Make this ivy compatible

### ISSUE THREAD

**Issue by sathwiq30** [gmazzamuto/ng2-google-charts#128]

**Comment by gmazzamuto** [comment]
Can you please elaborate more? As far as I understand, publishing Ivy libraries to npm is still discouraged. Perhaps you need to use `ngcc`?

**Comment by malafaya** [comment]
I'm not sure what the OP meant but I get this error on Angular 9 and Ivy:

> ng build --prod

ERROR in node_modules/ng2-charts/charts/charts.d.ts:53:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ng2-charts/ng2-charts) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see **if the library is expected to be compatible with Ivy**.

53 export declare class ChartsModule {
                        ~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by lazreg87** [comment]
@sathwiq30 might be referring to the error you now get when running Angular 10 and ngcc in the postinstall step:

```
ERROR in node_modules/ng2-google-charts/google-charts.module.d.ts:1:22

This likely means that the library (ng2-google-charts) which declares Ng2GoogleChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by lazreg87** [comment]
updating to latest version of ng2-google-charts solved the issue mentioned above for me at least
