### ISSUE TITLE
Compatibility with Angular 10

### ISSUE THREAD

**Issue by gsoulie** [gmazzamuto/ng2-google-charts#129]
Hi all,

I use ng2-google-chart since severals months with success, and today i'm trying to update my project from angular 8.1.3 to 10.

But during the angular updating, i get an issue with ng2-google-chart compatibility. 

So i tried to update it on 6.1.0 but i still get the following errors :

` Package "ng2-google-charts" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0" (extended), would install "10.2.2").
`
`
Package "ng2-google-charts" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.2.2").`

Here's my dependecies :

`
"dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/core": "^5.23.0",
    "@ionic-native/splash-screen": "^5.23.0",
    "@ionic-native/status-bar": "^5.23.0",
    "@ionic/angular": "^5.4.1",
    "angular-oauth2-oidc": "^9.2.2",
    "angular-oauth2-oidc-jwks": "^9.0.0",
    "chart.js": "^2.9.3",
    "core-js": "^2.5.4",
    "html2pdf.js": "^0.9.2",
    "ng2-google-charts": "^6.1.0",
    "ngx-pagination": "^5.0.0",
    "rxjs": "^6.6.3",
    "tslib": "^1.11.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "^0.803.29",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.3.29",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.2.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  },
`

So, is there any solution to get ng2-google-charts working on Angular 10 or i must stay in angular 8.x ?

Thanks

**Comment by gmazzamuto** [comment]
It does work on angular 10, I have tested it myself. I think you are having some conflicts with your dependencies, perhaps you could try to delete your `node_modules` folder altogether.

Or, you can clone this repository and launch the demo to see that it works with these commands:
```bash
npm i
ng build
ng serve
```
