### ISSUE TITLE
Upgrade to support Angular 13

### ISSUE THREAD

**Issue by ppartarr** [gmazzamuto/ng2-google-charts#143]
title says it all. Are there any new releases planned for this project? @gmazzamuto

**Comment by gmazzamuto** [comment]
I am working on that, some more testing and I'll make a new release. In the meantime, I think you can still use the current version with angular 13 if you install like this:
```
npm install --legacy-peer-deps ng2-google-charts
```

**Comment by jbellmont-phntm** [comment]
Hi @gmazzamuto do you have a rough timeline of when this will be released?

**Comment by gmazzamuto** [comment]
Hopefully only a couple of days, I'm finishing some compatibility tests across Angular versions

**Comment by gmazzamuto** [comment]
Hi, I have published new versions 6.2.0 and 7.0.0. Both should work with Angular 13
