### ISSUE TITLE
Google charts make webapp very slow about graphical rendering

### ISSUE THREAD

**Issue by mic24676** [gmazzamuto/ng2-google-charts#145]
We have an Angular 13 + ng2-google-charts 7 webapp on development.

I integrated a drag and drop angular material component. It perfectly works, very fluid, smooth and fun but since I integrated ng2-google-charts I noticed a problem about drag & drop: draggin is very jerky, no more smooth and fun.
If I hide the charts everything come back to be normal.
charts and drag&drap are in different component and I'm sure when I leave the charts component in reason of the drag&drop component the charts component have been destroyed (ngOnDestroy successfully runs for charts component).
At the moment ng2-google-charts are totally incompatible with my drag&drop weebapp and it's a big issue for our development. Is there anything you can do to make che charts our of memoery when a component is destroyed?

(Note: till some days ago the google charts were registered in the sessionStorage / localStorage along the webapp navigation but now I closed that function in reason of a worry about memoery in the HTML5 database but the problem persists)

**Comment by gmazzamuto** [comment]
I'm afraid that's something caused by the underlying Google Charts library, rather than this package which is simply a wrapper around it. Try to repeat this test by using Google Charts directly, rather than using ng2-google-charts. You can just copy and paste a snippet for example from [here](https://developers.google.com/chart/interactive/docs/gallery/histogram). If the problem persists, which I'm afraid it will, then unfortunately it is not something that can be easily fixed from my side.

**Comment by mic24676** [comment]
Ciao (italiano?) ho provato l'integrazione attraverso la metodologia
classica di caricamento dei charts di Google in JS ma con lo stesso
identico esito. I charts di Google "fanno qualcosa al DOM o al motore del
broswer" tale da rendere il successivo drag & drop scattoso.
Io non ho competenza oltre la programmazione/sviluppo. Non ho idea di dove
e come i charts di Google possano andare a creare un collo di bottiglia nel
motore del browser. Qualche indicazione?

Hi there, I tried thought the classic loading method for Google charts in
Javascript app but the result is exactly the same. Google charts make
something to ther DOM or to the browser engine, result: jerky drag & drop!
I have no competencies over the programming/developing so I don't know
where to go o check or what I have to search for a solution. Any idea?

Mic

Il giorno gio 20 gen 2022 alle ore 20:02 Giacomo Mazzamuto <
***@***.***> ha scritto:

**Comment by gmazzamuto** [comment]
Il problema è che i grafici di Google Charts sono resi come un documento `<svg>`, il che ovviamente appesantisce l'albero DOM. Usando la developer console del browser si possono chiaramente vedere tutti i nodi svg di un grafico Google Charts.

Google Charts are rendered as an `<svg>` document which of course translates in a heavier DOM tree.

See also #125.

Closing for now since this issue seems to be related to the underlying Google Charts library.

**Comment by mic24676** [comment]
Buongiorno Giacomo,
grazie per il suggerimento ma ho tentato alcune strade e ancora nessun
successo:

   - usato il metodo ngOnDestroy(), all'uscita del componente che include
   il grafico per
      - svuotare il div che contiene il grafico:
      $('#selector').empty().remove() (jQuery)
      - eliminare la mia variabile che contiene i dati del grafico
      - eliminare l'elemento "component" <google-chart tramite
      reference @ViewChild
      - svuotato (google = {}) la variabile google dichiarata nel file .ts
      - cercato e tentato di rimuovere i listener dei grafici di google
      chart

Nulla di tutto questo ha avuto effetto sull'enorme rallentamento che il
componente google-chart causa sul sistema a livello globale.
Se puoi ti chiedo la cortesia di mettermi sulla strada per capire su cosa
posso intervenire perché lo scopo è che, alla chiusura del componente che
contiene il grafico, il sistema si liberi di tutto quello che il modulo
google chart può avere fatto/alterato per causare il rallentamento evidente
di tutte le animazioni JS/CSS

Nota: ho visto che esiste (o esisteva) una funzione clearChart() per
svuotare il grafico ma non riesco ad usarla in Angular 13. Puoi mettermi
sulla strada?

Io mi trovo ad un passo dalla release della webapp e non credo di poter
cambiare piattaforma ed usare grafici che non siano google chart per cui ho
l'impellente necessità di risolvere. Se potessi darmi un aiuto te ne sarei
molto molto grato.

Un caro saluto.

Mic

Il giorno ven 21 gen 2022 alle ore 19:01 Giacomo Mazzamuto <
***@***.***> ha scritto:

**Comment by gmazzamuto** [comment]
`clearChart()` non è una funzione di questo pacchetto, è una funzione della libreria Google Charts. Per chiamarla devi prima ottenere il [`ChartWrapper`](https://developers.google.com/chart/interactive/docs/reference#chartwrapperobject) come spiegato [qui](https://github.com/gmazzamuto/ng2-google-charts/blob/57e71826cec51011818f1be29abd15326bd0e4f0/doc/Advanced_usage.md), in fondo. Poi puoi chiamarla così:
```typescript
ccWrapper.getChart().clearChart();
```

Ammesso che ci sia una soluzione a questo problema, come dicevo prima ti conviene (per fare questi test) usare la libreria Google Charts direttamente, senza usare `ng2-google-charts`. Se a un certo punto riesci a risolvere il problema usando direttamente la libreria, poi posso aiutarti ad applicare la soluzione anche usando `ng2-google-charts`.

In alternativa prova a vedere se la cosa migliora installando la versione di `ng2-google-charts` che si trova sul ramo [memory-leak-2](/gmazzamuto/ng2-google-charts/tree/memory-leak-2). è una versione in cui ho provato a rilasciare quante più risorse possibili, per cercare di mitigare questo problema. Ma non è detto che funzioni, infatti sono noti da tempo [problemi di questo tipo](https://github.com/google/google-visualization-issues/issues?q=is%3Aissue+is%3Aopen+dom) con Google Charts.

è chiaro comunque che questo problema dipende da Google Charts direttamente, quindi purtroppo non c'è molto che io possa fare...

**Comment by mic24676** [comment]
Ciao,
mi fa piacere informarti che ieri notte sono riuscito a risolvere i
problemi di peso del sistema a seguito dell'uso dei grafici, integrando
direttamente la libreria e poi, al ngOnDestroy() applicare .clearChart() su
ogni grafico istanziato e questo risolve totalmente il problema.
Grazie per il supporto. Mi ha fatto piacere aver avuto il tuo supporto.
Mic


Il giorno mar 25 gen 2022 alle ore 00:11 Giacomo Mazzamuto <
***@***.***> ha scritto:

**Comment by gmazzamuto** [comment]
Ottimo.

Ho provato a implementare ` ngOnDestroy()` in modo che `clearChart()` venga chiamata ogni volta che la componente viene distrutta. Puoi provare a scaricare e installare questa versione: [ng2-google-charts-7.0.1-alpha.0.tar.gz](https://github.com/gmazzamuto/ng2-google-charts/files/7937565/ng2-google-charts-7.0.1-alpha.0.tar.gz) e vedere se così si risolve il problema? (senza cioè che sia l'utente a dover chiamare `clearChart()`). Se dovesse funzionare lo rilascio nella versione 7.0.1.

Per installare è sufficiente `npm install ng2-google-charts-7.0.1-alpha.0.tar.gz`

**Comment by mic24676** [comment]
Ciao Giacomo
non appena potrò ritagliarmi un minimo di tempo sarà un piacere provarlo.
L'installazione della versione alpha fa l'override sulla versione stabile?
o posso implementare specificatamente la versione alpha in parallelo alla
versione stabile?

Mic

Il giorno mar 25 gen 2022 alle ore 23:19 Giacomo Mazzamuto <
***@***.***> ha scritto:

**Comment by gmazzamuto** [comment]
Esatto, se fai `npm install` sovrascrive la versione installata
