### ISSUE TITLE
MouseOver and mouseOut don't work with GeoChart type

### ISSUE THREAD

**Issue by Krivobarac** [gmazzamuto/ng2-google-charts#150]
I didn't look does mouseOver and mouseOut work with other types but I noticed that those events do nothing with GeoChart type. Is that normal behavior?

**Comment by gmazzamuto** [comment]
That's because `GeoChart` doesn't have `onmousover` Events:

https://developers.google.com/chart/interactive/docs/gallery/geochart#events
