### ISSUE TITLE
Controllers for Google Charts

### ISSUE THREAD

**Issue by davidfawcett** [gmazzamuto/ng2-google-charts#17]
Firstly, thanks for writing this project, it was very helpful for getting started.

I was wondering if it was possible to add Google Charts controllers for charts using Ng2 Google Charts?

Specifically I was wondering if it was possible to add things like the Chart Range Filter and use Aggregate data?

**Comment by gmazzamuto** [comment]
Hi, thanks for your interest in the package!
It would be a nice addition, but unfortunately my time is limited at this very moment so I can't promise... I'm leaving the issue open, let's see if someone is willing to help!

I'm also dropping this link for my personal reference for the future:
[https://developers.google.com/chart/interactive/docs/gallery/controls](https://developers.google.com/chart/interactive/docs/gallery/controls)
