### ISSUE TITLE
Is there a way to cleanly clear/destroy a chart?

### ISSUE THREAD

**Issue by blakeparkinson** [gmazzamuto/ng2-google-charts#20]
There are cases where I need to redraw a chart from scratch, wondering the best way to do this?

**Comment by gmazzamuto** [comment]
Can you please try with the solution posted in #6?

**Comment by blakeparkinson** [comment]
Thanks @gmazzamuto. Doesn't seem to fully work.

I have a use case, where users will be resetting the chart, and even changing chart types on the fly.

I ended up hacking around it, by adding a new output method that I call, which allows me to wipe out the google chart wrapper. This way, when it hits the ngOnChanges function call, it initializes a whole new chart for me (because the old wrapper doesn't exist)

If this is something that you think might be a useful addition for others, I'd be happy to submit a PR

**Comment by gmazzamuto** [comment]
Fixed in the latest version, please see the first example in the updated demo
