### ISSUE TITLE
Question: How can I use Google Formatter?

### ISSUE THREAD

**Issue by souravmondal93** [gmazzamuto/ng2-google-charts#21]
Thanks for this awesome project. I want to use the Google Formatter, but I am unable to do so.

In Google Charts, we can use something like this to format that data. What do we need to do in this project to achieve the same result?

```javascript
var data = new google.visualization.arrayToDataTable(chartData, false);
var formatter = new google.visualization.NumberFormat({
	pattern: '#.##%' 
});
formatter.format(data, 1);
var chart = new google.visualization.BarChart(document.getElementById('poll-result'));
```
Thanks

**Comment by gmazzamuto** [comment]
Added support for formatters in version 2.3.0

**Comment by souravmondal93** [comment]
Thanks @gmazzamuto :)

**Comment by lutchit** [comment]
Hello, 
Is the implementation of this issue allows to use `google.visualization.arrayToDataTable` as data table format ?
Thank you.
