### ISSUE TITLE
Can't bind to 'data' since it isn't a known property of 'google-chart'.

### ISSUE THREAD

**Issue by tafint** [gmazzamuto/ng2-google-charts#22]
I use this package for angular 2
I have configed in app.module.ts

> import { Ng2GoogleChartsModule } from 'ng2-google-charts';
> @NgModule({
>   ...
>   imports: [
>     ...
>     Ng2GoogleChartsModule,
>   ],
> })
> export class AppModule { }
> 

in package.json

>     "@angular/animations": "^4.1.1",
>     "@angular/common": "^4.0.0",
>     "@angular/compiler": "^4.0.0",
>     "@angular/core": "^4.0.0",
>     "@angular/forms": "^4.0.0",
>     "@angular/http": "^4.0.0",
>     "@angular/platform-browser": "^4.0.0",
>     "@angular/platform-browser-dynamic": "^4.0.0",
>     "@angular/router": "^4.0.0",
>     "bootstrap": "^3.3.7",
>     "chart.js": "^2.5.0",
>     "core-js": "^2.4.1",
>     "flag-icon-css": "^2.8.0",
>     "jquery": "^3.2.1",
>     "ng2-datepicker": "^1.8.3",
>     "ng2-dnd": "^4.0.2",
>     "ng2-tag-input": "^1.2.6",
>     "rxjs": "^5.1.0",
>     "zone.js": "^0.8.4"

but i get issue: Can't bind to 'data' since it isn't a known property of 'google-chart'.

**Comment by gmazzamuto** [comment]
I am sorry, this looks like a problem in your setup rather than an issue with the package. I just tried with your package.json and it works fine for me. Try setting up your project with `@angular/cli`, maybe it can help. By the way, you didn't specify how you are compiling
