### ISSUE TITLE
Chart not loading on actual device

### ISSUE THREAD

**Issue by kunalailani** [gmazzamuto/ng2-google-charts#24]
hey admin,
 Chart is displayed in browser, but not in actual device. I'm Not able to figure out need your help.

Thank you.

**Comment by gmazzamuto** [comment]
I can't understand what you say. Do you mean it doesn't work on mobile devices? I tested it on Android, both Chrome and Firefox and it works

**Comment by kunalailani** [comment]
@gmazzamuto Thanks for your reply.
Yes it doesn't work on mobile devices.  I tested the same on Android L,M.
Following is the system/environment info.

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.10.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
