### ISSUE TITLE
How could I change the size of the chart

### ISSUE THREAD

**Issue by idl-hanzhang** [gmazzamuto/ng2-google-charts#27]
Hello, 
    I checked your docs and did not find any way to make my chart bigger. For example , I want to make my chart as high as 900 px, but I can not find place to set it, it can only show as 200px.

**Comment by gmazzamuto** [comment]
Please use `width` and `height` in the chart options, as documented in [Google Chart's documentation](https://developers.google.com/chart/interactive/docs/basic_customizing_chart).

Example:
```typescript
  public columnChartOptions:any =  {
    chartType: 'ColumnChart',
    dataTable: [
      ['Country', 'Performance', 'Profits'],
      ['Germany', 700, 1200],
      ['USA', 300, 600],
      ['Brazil', 400, 500],
      ['Canada', 500, 1000],
      ['France', 600, 1100],
      ['RU', 800, 1000]
    ],
    options: {title: 'Countries', height: 1000}
  };
```
