### ISSUE TITLE
slices option in pie chart does not appear to be working

### ISSUE THREAD

**Issue by pranav-xx** [gmazzamuto/ng2-google-charts#28]
Hi
I am trying to use ng2-google-charts to paint a pie chart

I am not able to define colors for slices. My options look like this

> pieChartOptions = {
>       chartType: 'PieChart',
>       dataTable : this.pieChartData,
>       slices: {
>         0: {
>           fill: `'#000000'`
>         }
>       }
>     }
> 

Please suggest

Thanks,
Pranav Kaushik

**Comment by gmazzamuto** [comment]
The `slices` property must be nested inside `options`:

```typescript
  public pieChartOptions:any =  {
    chartType: 'PieChart',
    dataTable: [
      ['Task', 'Hours per Day'],
      ['Work',     11],
      ['Eat',      2],
      ['Commute',  2],
      ['Watch TV', 2],
      ['Sleep',    7]
    ],
    options: {
      title: 'Tasks',
      slices: {
        0: {
        offset: 0.5
        }
      }
    }
  };
```
