### ISSUE TITLE
Use dates, specify columns like in Annotated Timeline example

### ISSUE THREAD

**Issue by fedorbirjukov** [gmazzamuto/ng2-google-charts#30]
Is it possible to create something like that?

https://developers.google.com/chart/interactive/docs/gallery/annotatedtimeline

**Comment by Omniwoof** [comment]
Yup! I'm using it myself.

Set 'chartType: 'AnnotationChart' and then format your data as per the instructions that you linked.

I haven't worked out how to use the 'rangechange' event that comes with it. You need to reference the name of the chart which should be 'this.wrapper' except that it's out of scope. Working out how to fix that at the moment.
