### ISSUE TITLE
Horizontal scroll not working in column chart

### ISSUE THREAD

**Issue by rajamuthur** [gmazzamuto/ng2-google-charts#33]
![columnchart_horizontal scroll](https://user-images.githubusercontent.com/10390662/27179146-f1037552-51ea-11e7-885a-a67966ccf3fe.png)
I have created new column chart.

**Option object is:**

options: {
                title: 'Company Performance',
                 explorer: { axis: 'vertical' },
                  explorer: { axis: 'horizontal' },
                 chartArea: {
            		 	width:'90%',
            		 	height:'60%'
            		 }
            }

**Data table is:**
  dataTable: [
                ['Year', 'Sales', 'Expenses', 'Profit'],
                ['1998', 1030, 540, 350],
                ['1999', 1000, 400, 200],
                ['2000', 1170, 460, 250],
                ['2001', 660, 1120, 300],
                ['2002', 1030, 540, 350],
                ['2003', 1030, 540, 350],
                ['2004', 1030, 540, 350],
                ['2005', 1000, 400, 200],
                ['2006', 1170, 460, 250],
                ['2007', 660, 1120, 300],
                ['2008', 1030, 540, 350],
                ['2009', 1000, 400, 200],
                ['2010', 1170, 460, 250],
                ['2011', 660, 1120, 300],
                ['2012', 1030, 540, 350],
                ['2013', 1030, 540, 350],
                ['2014', 1000, 400, 200],
                ['2015', 1170, 460, 250],
                ['2016', 660, 1120, 300],
                ['2017', 1030, 540, 350]
         ] 

**Chart type is:**

chartType: 'ColumnChart'

**ISSUE:**
Horizontal scroll is not working in column chart. But vertical chart is working as expected even Zoom also working.

If i use google-chart then both scroll is working as expected.

**Comment by viswanathamsantosh** [comment]
same for me! horizontal not working on multi line chart.

**Comment by pmassu** [comment]
Same also for me. Vertical explorer works on column chart but horizontal does nothing even on a single line chart.

**Comment by felipecespedes** [comment]
@rajamuthur some things I notice from your code:
- you have the `explorer` option twice
- the explorer only works with continuous axes (such as numbers or dates). See https://developers.google.com/chart/interactive/docs/gallery/columnchart#configuration-options

so in order to make it work, you should update your data as follows:

```ts
options: {
  title: 'Company Performance',
  explorer: { actions: ['dragToPan'] },
  chartArea: {
    width: '90%',
    height: '100%'
  }
}
```
```ts
dataTable: [
  [{label: 'Year', type: 'number'}, 'Sales', 'Expenses', 'Profit'],
  ['1998', 1030, 540, 350],
  ['1999', 1000, 400, 200],
  ['2000', 1170, 460, 250],
  ['2001', 660, 1120, 300],
  ['2002', 1030, 540, 350],
  ['2003', 1030, 540, 350],
  ['2004', 1030, 540, 350],
  ['2005', 1000, 400, 200],
  ['2006', 1170, 460, 250],
  ['2007', 660, 1120, 300],
  ['2008', 1030, 540, 350],
  ['2009', 1000, 400, 200],
  ['2010', 1170, 460, 250],
  ['2011', 660, 1120, 300],
  ['2012', 1030, 540, 350],
  ['2013', 1030, 540, 350],
  ['2014', 1000, 400, 200],
  ['2015', 1170, 460, 250],
  ['2016', 660, 1120, 300],
  ['2017', 1030, 540, 350]
]
```

See a working demo here https://codesandbox.io/s/horizontal-and-vertical-panning-dvwtg
