### ISSUE TITLE
Click to drag doesn't appear to work with touch event on mobile?

### ISSUE THREAD

**Issue by JamieWritesCode** [gmazzamuto/ng2-google-charts#35]
Perhaps I'm doing something wrong however I can't seem to get a chart to respond to a drag event on a mobile device. The touch event works for selecting elements on the chart but dragging will not scroll, even with correctly configured viewWindow and explorer options.

This is easily reproduce-able and testable by creating a chart with a defined viewWindow and then using the Chrome DevTools device toolbar to emulate a phone.

Clicking and dragging on desktop works, however doing the same action with a touch event does not.

Any thoughts?

**Comment by TehCrucible** [comment]
Quick follow up to this: it appears this is an issue on the underlying Google Charts library and not this wrapper. Not sure how best to tackle this now. I've got touch events being passed from the chart into my class now however I can't find a good way to programtiaclly 'pan' the chart from the Google Charts api.

**Comment by pgorod** [comment]
Sorry, I know this is an old Issue, but...

> I've got touch events being passed from the chart into my class now 

**How did you get this?** I can't do this part...

> however I can't find a good way to programtiaclly 'pan' the chart from the Google Charts api.

Hey, I can do this part! You just need to use `control.setState`, look for examples online. Make sure you use dates that fall within the maximum range of data available to the chart.
