### ISSUE TITLE
Chart is rebuilt from scratch when data is changed

### ISSUE THREAD

**Issue by mflorence99** [gmazzamuto/ng2-google-charts#36]
I noticed this because my animations aren't running smoothly as new data is pushed to the chart. I think line 75 in `google-chart.component.ts` is wrong. It should read (I believe):

```ts
if (this.wrapper === undefined || this.wrapper.getChartType() !== this.data.chartType) {
```

Note the parens after `this.wrapper.getChartType` to actually execute the method call. 

I had a chance to check this out and I've made a pull request.

**Comment by gmazzamuto** [comment]
makes sense! Thanks for your PR

2017-07-12 11:56 GMT+02:00 Mark Florence <notifications@github.com>:
