### ISSUE TITLE
Use with lazy load can trigger load-twice exception 

### ISSUE THREAD

**Issue by mflorence99** [gmazzamuto/ng2-google-charts#38]
Consider Ng2GoogleChartsModule imported into a lazily-loaded module and also into an eagerly-loaded feature module. If the lazily-loaded module is routed to at startup, then the Google charts code can throw an error warning that the chart code cannot be loaded multiple times.

This is kind of an odd-ball case but I stumbled into it as soon as I switched our app's pages to lazy load. I have a fix that eliminates the error and I'll submit a PR for it. 

My change feels a little hacky and I'll be very interested in better alternatives!

**Comment by viwell** [comment]
Hi @mflorence99 , have you tried to import this library just once inside of a shared module instead of import it in every lazily loaded module?

**Comment by mflorence99** [comment]
Yes -- now I have and that was a very good suggestion. If I import Ng2GoogleChartsModule in such a module -- a common module that is imported into the main app and into the lazily-loaded modules -- and re-export it, all works well.

My only quibble is that I kind of have to know as a consumer that there should only be one instance of `GoogleChartsLoaderService`. Otherwise, my original arrangement of modules would be legitimate.

But that's just a quibble and TBH I'm quite happy to abandon my PR and move on, especially in the light of your other objections to it.

Many thanks!
