### ISSUE TITLE
How can i redraw bar chart?

### ISSUE THREAD

**Issue by brendaniel** [gmazzamuto/ng2-google-charts#4]
Hi gmazzamuto,

**html**
<google-chart [data]="columnChartOptions"></google-chart>

**component.ts**
columnChartOptions =  {
    chartType: 'ColumnChart',
    dataTable: this.statData,
    options: {'title': 'Chart'}
 };

this.statData // initalize after ngOnInit

how can i redraw the google-chart graph?

**Comment by gmazzamuto** [comment]
you have to force a reference update like this:
```typescript
// force a reference update (otherwise angular doesn't detect the change)
this.columnChartOptions = Object.create(this.columnChartOptions);

// update with new data
this.columnChartOptions.dataTable = yourNewDataTable;
```

Please see also the [demo page](https://gmazzamuto.github.io/ng2-google-charts) and in particular this [line of code](../blob/master/demo/src/app/app.component.ts#L75).
