### ISSUE TITLE
How to embed a routerLink in a table cell?

### ISSUE THREAD

**Issue by westwick** [gmazzamuto/ng2-google-charts#40]
I'm using `chartType: 'Table'` and trying to have one of the cells be a router link. I've tried a bunch of stuff including using formatters but can't get any of it to work. I simply need a table cell to be formatted like `<a [routerLink]="/whatever">Link</a>` which seems like it should be easy to do. Any suggestions?

**Comment by westwick** [comment]
I should mention that I can accomplish similar functionality by binding to the `(chartSelect)` event and hooking that to a function on my component which will call route.navigate, but this applies to the whole row which prevents me from having different links on the same row. Additionally because it's not a real routerLink, it loses some of the functionality you'd expect from a normal anchor tag such as showing the link name at the bottom of the window on hover. Hope this all makes sense.

**Comment by gmazzamuto** [comment]
This package is just a wrapper for the [Google Charts](https://developers.google.com/chart) library. The library itself has nothing to do with Angular, so I doubt one can add Angular-related functionalities such as router links inside a chart.
