### ISSUE TITLE
Question: How to set null values?

### ISSUE THREAD

**Issue by lutchit** [gmazzamuto/ng2-google-charts#42]
Hello, 

I would like to know how setting null values in a dataTable like in this example:

```
dataTable: [
['Task ID', 'Task Name', 'Start Date', 'End Date', 'Duration', 'Percent Complete', 'Deependencies'],
['1', 'Task 1', new Date(2016,0,1), new Date(2016,0,2), 200, 100, null],
['2', 'Task 2', new Date(2016,0,2), new Date(2016,0,3), null, 20, '1'],
]
```

For the moment, I have an error: 

`All series on a given axis must be of the same data type`

Thank you in advance.

**Comment by Omniwoof** [comment]
I'd say you have to set the Null value to 0 in that example. The error is
saying that you are comparing different data types, like numbers compared
to strings. In JS 'null' is of the data type 'null' so it doesn't count as
a number.

**Comment by lutchit** [comment]
Here is an other example:

```
dataTable: [
      ['Time', 'Field1', 'Field2', 'Error'],
      [new Date(Date.now()), 10, 20, 10],
      [new Date(Date.now()), 15, 25, null]
    ]
```

After that, I replace values in Error column by a start with this line:

```
this.lineChartData.options.series = [{ targetAxisIndex: 0 }, { targetAxisIndex: 1 }, { lineWidth: 0, targetAxisIndex: 1, pointShape: 'star', pointSize: 20,interpolateNulls: true}]; 
```

In this example, I have an error in my first line of data, but I don't want to have one for the second line, it's why I want to set the value to null. Using a 0 as value, a start will appear whereas there is not an error. Do you understand ?

**Comment by gmazzamuto** [comment]
The following works for me:
```typescript
 public lineChartData: =  {
    chartType: 'LineChart',
    dataTable: [
      ['Year', {label: 'Sales', type: 'number'}, {label: 'Expenses', type: 'number'}],
      ['2004',  1000,      null]
    ],
    options: {title: 'Company Performance'}
  };
```
