### ISSUE TITLE
mouseover throws error for piechart / donutchart

### ISSUE THREAD

**Issue by beuntje** [gmazzamuto/ng2-google-charts#46]
`<google-chart [data]="pieChartData" (mouseOver)="mouseOver($event)"></google-chart>`
...
```
this.pieChartData = {
    "chartType": "PieChart",
    "dataTable": [["Title", "Value"], ["A", 80], ["B", 10], ["C", 30]],
    "options": {
         "height": 300,
    }
}

mouseOver(e?)  {
        console.log("mouseover", e);
 }
```

throws following error: 

> EXCEPTION: Invalid column index null. Should be an integer in the range [0-1].

I guess it's because in  `private parseMouseEvent` (src/google-chart/google-chart.component.ts) , code tries to get values like columnType and columnLabel that do not exist for piecharts...

**Comment by Suvikr23** [comment]
@beuntje were you able to find any workarounds for this?
