### ISSUE TITLE
[data] not a known property of google-chart component @v3.2.0

### ISSUE THREAD

**Issue by CramericaIndustries** [gmazzamuto/ng2-google-charts#48]
v3.2.0 is broken. On startup I got that error message. After I downgraded to v3.1.0 everything works fine now.

**Comment by gmazzamuto** [comment]
It works for me, it must be something else. If you look at the code you'll see that there is only one commit between v3.1.0 and v3.2.0 dealing with internationalization and locale. It's unlikely to have broken anything

**Comment by luizbag** [comment]
I just had the same issue on V3.3.0 but just when running tests. I run "ng serve" and it works. With "ng test" it shows the message that data is not a known property of google-chart-component.
