### ISSUE TITLE
Timeline chart: 1st data is not showing

### ISSUE THREAD

**Issue by misisriddle** [gmazzamuto/ng2-google-charts#53]
I have the following code that I am trying out.

```
timelineChartData =  {
    chartType: 'Timeline',
    dataTable: [
      [ 'Washington', new Date(1789, 3, 29), new Date(1797, 2, 3) ],
      [ 'Adams', new Date(1797, 2, 3),  new Date(1801, 2, 3) ],
      [ 'Jefferson', new Date(1801, 2, 3),  new Date(1809, 2, 3) ]
    ],
    options: {
      'title': 'Tasks'
    },
  };
```

But I only see Adams and Jefferson. Washington is not showing. Any idea why?

**Comment by tfernandescunha** [comment]
the first line of the chart is the chart definition:
dataTeste = {
		chartType: 'Timeline',
		dataTable: [
			['Name', 'From', 'To'],
			['Washington', new Date(1789, 3, 30), new Date(1797, 2, 4)],
			['Adams', new Date(1797, 2, 4), new Date(1801, 2, 4)],
			['Jefferson', new Date(1801, 2, 4), new Date(1809, 2, 4)]
		]
	};
