### ISSUE TITLE
Does this package supports 5 columns data in Timeline Chart?

### ISSUE THREAD

**Issue by dsandeepchary** [gmazzamuto/ng2-google-charts#58]
Like the original google charts, does this package also supports 5 columns data iin Timeline Chart?
If so, can you add this support?
Reference: [Google Timeline Data](https://developers.google.com/chart/interactive/docs/gallery/timeline#data-format)

**Comment by SayakMukhopadhyay** [comment]
No, it does not. It supports a maximum of 4 columns. I believe tooltip is left out.

**Comment by dsandeepchary** [comment]
@SayakMukhopadhyay, Is there any way we can show customised content in tooltip?

**Comment by SayakMukhopadhyay** [comment]
I wouldn't know. I just tested out your requirement and a clear error asking for 4 inputs was shown.

**Comment by gmazzamuto** [comment]
It does, please see #91
