### ISSUE TITLE
Chart not refreshing when pusshing new data in the data table

### ISSUE THREAD

**Issue by ugobriasco** [gmazzamuto/ng2-google-charts#6]
I'm creating a gantt chart as following:

```
chart = {
  chartType: 'Gantt',
  dataTable: [
['Task ID', 'Task Name', 'Start Date', 'End Date', 'Duration', 'Percent Complete', 'Deependencies'],
['1', 'Task 1', new Date(2016,0,1), new Date(2016,0,2), 200, 100, null],
['2', 'Task 2', new Date(2016,0,2), new Date(2016,0,3), null, 20, '1'],

],
  options:{
    title: 'Project',
    height: 275,
  }
}
```

Unfortunately, by pushing a new `Task` in the `dataTable`, the gantt chart is not refreshed and it still contains just the original tasks

[here](https://github.com/ugobriasco/go-gantt/blob/gh-pages/src/app/chart/chart.component.ts) my code

**Comment by gmazzamuto** [comment]
you have to force a reference update like this:

```typescript
// force a reference update (otherwise Angular doesn't detect the change)
this.chart = Object.create(this.chart);

// update with new data
this.chart.dataTable = yourNewDataTable;
```

See also the [demo page](https://gmazzamuto.github.io/ng2-google-charts).

**Comment by blakeparkinson** [comment]
Thanks @gmazzamuto. Doesn't seem to fully work.

I have a use case, where users will be resetting the chart, and changing chart types on the fly.

I ended up hacking around it, by adding a new output that I call, which allows me to wipe out the google chart wrapper.  This way, when it hits the ngOnChanges function call, it initializes a whole new chart for me.

If this is something that you think might be a useful addition for others, I'd be happy to submit a PR
