### ISSUE TITLE
chart does not update when data is changed

### ISSUE THREAD

**Issue by shaozi** [gmazzamuto/ng2-google-charts#61]
I am using the sample pie chart:

```
public pieChartData =  {
    chartType: 'PieChart',
    dataTable: [
      ['Task', 'Hours per Day'],
      ['Work',     11],
      ['Eat',      2],
      ['Commute',  2],
      ['Watch TV', 2],
      ['Sleep',    7]
    ],
    options: {'title': 'Tasks'},
  };
```

However, later if I change `this.pieChartData.dataTable[1][1] = 100`, the chart does not update.

**Comment by mppfiles** [comment]
You must force a chart redraw. I used it like this:

```javascript
this.cchart.wrapper.setDataTable(this.pieChartData.dataTable);
this.cchart.redraw();
```

**Comment by shaozi** [comment]
yes it works!

**Comment by chr1soscl** [comment]
where do you place these additional lines?
ts:
this.releases=[['Id','Name','Description','Type','Year','Month','Active']];
this.releaseService.getAll().subscribe(
      releasesResp=>{
        releasesResp.forEach(element => {
              this.releases.push([element.release_id,
                                  element.release_name,
                                  element.release_description,
                                  element.release_type_id, 
                                  element.year_name+'', 
                                  element.month_id, 
                                  element.active]);
        });

public releasesTableChart =  {
    chartType: 'Table',
    dataTable: this.releases,
    options: {
      title: 'Releases', 
      allowHtml: true,
      alternatingRowStyle: true,
      pageSize:10,
      width:'100%'      
    }
  };
html:
<google-chart [data]="releasesTableChart"></google-chart>
mine prints the columns line, but it does not prints the data coming from the Rest API.

**Comment by gmazzamuto** [comment]
Please see the [demo](https://www.devrandom.it/software/ng2-google-charts/demo/), it shows how data can be changed programmatically (you need to force a redraw).

**Comment by Rithvik-Reddy** [comment]
I have a case where I have to redraw the chart after unhiding the parent div. The chart when drawn in the hidden div seems to have an issue while calculating the width and few other variables. That seems to be the issue with google charts it self.
 The draw function works as expected when there is a change in data but it doesn't redraw to adjust the width of columns when there is no change in data. Is there something I can do to redraw/refresh the chart in this context?
