### ISSUE TITLE
[Question] GeoChart markers only showing when page is refreshed

### ISSUE THREAD

**Issue by rafaelcgdf** [gmazzamuto/ng2-google-charts#63]
Hi,

I'm trying to load dynamic data on the GeoChart, I'm doing a service call on ngOnInit to retrieve lat/long and updating the dataTable with that info.
It all works fine when I load the page using F5, the chart is loaded and the markers are all loaded dynamically but when I go to the page through routing (from another component), the chart is loaded empty (no markers even tough the service call was made).

```typescript
export class DummyComponent implements OnInit {
   public geoChartData = {
        chartType: 'GeoChart',
        dataTable: [
            ['Latitude', 'Longitude', 'Description'],
            [0, 0, '']
        ],
        options: {
            'region': '154',
            'displayMode': 'markers'
        }
   };
   
  constructor(private dummyService: DummyService) { }
   
  public ngOnInit(): void {
      this.dummyService.getData().subscribe(data => {
          const placesMap = data.map(place => ([
                  latitude,
                  longitude,
                  'description'
          ]));
       this.geoChartData.dataTable = [
                ['Latitude', 'Longitude', 'Description'],
                ...placesMap
       ];
    });
  }
}
```

- Do I need to call the redraw in order to solve this? If yes, where would it be best placed?
- Is the way I structured the code wrong? Should it be done in a different way?

**Comment by gmazzamuto** [comment]
Yes, you probably need to force a redraw of the chart using something similar to this:
```typescript
let geoComponent = this.geoChartData.component;

geoComponent.draw();  // force a redraw
```
