### ISSUE TITLE
chart.redraw() does not (re-)format DataTable columns

### ISSUE THREAD

**Issue by nebucaz** [gmazzamuto/ng2-google-charts#64]
### Steps to reproduce

1) carting LineChart with formatters
```typescript
    formatters: [{
        columns: [1, 2, 3],
        type: 'NumberFormat',
        options: {
          groupingSymbol:'\'',
          decimalSymbol: '.',
          fractionDigits: 0,
          prefix: 'CHF ', negativeColor: '#FF0000', negativeParens: true
        }}
```
<img width="171" alt="screen shot 2018-02-04 at 16 09 53" src="https://user-images.githubusercontent.com/961682/35778995-856f3f80-09c6-11e8-97c8-5c2e37d6fbc3.png">
2) change data

```typescript
this.cchart.wrapper.setDataTable(this.lineChartData.dataTable);
```

3) redraw() 
```typescript
this.cchart.redraw();
```

### Defined Format is lost
<img width="186" alt="screen shot 2018-02-04 at 16 10 04" src="https://user-images.githubusercontent.com/961682/35779002-a377caba-09c6-11e8-8f21-c55273c4112f.png">

 [Google documentation](https://developers.google.com/chart/interactive/docs/reference#formatters) states, that one has to reformat data before it can get displayed. This is done once (when the chart is loaded) in `ngOnChanges()` (`google-chart.component.js`) which applies formatters to the given columns. But as far as I can tell, reformatting isn't done/triggered by `redraw()`. 

As a quick workaround I forked the repo and implemented a `format()` function which is called before `redraw()`. 

in `google-chart.component.js `

```typescript
    GoogleChartComponent.prototype.format = function () {
        var _this = this;
        if (_this.data.formatters !== undefined) {
            for (var _i = 0, _a = _this.data.formatters; _i < _a.length; _i++) {
                var formatterConfig = _a[_i];
                var formatterConstructor = google.visualization[formatterConfig.type];
                var formatterOptions = formatterConfig.options;
                var formatter = new formatterConstructor(formatterOptions);
                for (var _b = 0, _c = formatterConfig.columns; _b < _c.length; _b++) {
                    var col = _c[_b];
                    formatter.format(_this.wrapper.getDataTable(), col);
                }
            }
        }
        _this.redraw();
    }
```

then:

```typescript
       this.cchart.format();
       this.cchart.redraw();
```
Another solution would be to trigger reformatting in the `redraw()` function or to expose google.visualization API and/or the formatter constructor. What do you think?

**Comment by gmazzamuto** [comment]
Hi,

thank you for your contribution.

The option to trigger reformatting in the `redraw()` function seems interesting. However, the example that you provide is compiled javascript rather than source typescript. If you want automatic formatting to be included in the package, please provide the typescript implementation and submit a pull request.

thanks a lot
