### ISSUE TITLE
ERROR in Metadata version mismatch for module ng2-google-charts

### ISSUE THREAD

**Issue by prasyell7** [gmazzamuto/ng2-google-charts#69]
Here is the list of some of modules from my package.json:
    _

> "@angular/common": "^4.2.4",
>     "@angular/compiler": "^4.2.4",
>     "@angular/core": "^4.2.4",
>     "@angular/platform-browser": "^4.2.4",
>     "@angular/platform-browser-dynamic": "^4.2.4",
>     "@angular/router": "^4.2.4",
>     "@ngrx/core": "^1.2.0",
>     "@ngrx/router": "^1.0.0-beta.2",
>     "ng2-google-charts": "^3.3.0",

_

It was working fine until 02/16/2018. But now it started throwing the below error:

> _**ERROR in Metadata version mismatch for module /jenkins/..../node_modules/ng2-google-charts/index.d.ts, found version 4, expected 3.**_

This is stopping my build and deployment. Please help me.

**Comment by gmazzamuto** [comment]
I think the issue can be solved if you upgrade angular to version 5 or downgrade ng2-google-charts to version 3.3.0 (probably you have 3.4.0 now)
