### ISSUE TITLE
chartReady not working

### ISSUE THREAD

**Issue by jagomf** [gmazzamuto/ng2-google-charts#72]
chartReady does not seem to be working, at least for a GeoChart.

**Comment by felipecespedes** [comment]
@jagomf do you have more information about this error?

I'm seeing the `chartReady` event working, please see this working demo https://codesandbox.io/embed/on-ready-event-39b49

**Comment by jagomf** [comment]
I don't remember what was happening 18 months back when I tested... but it seems to be working now.
