### ISSUE TITLE
Has mouseOver ever worked in a GeoChart?

### ISSUE THREAD

**Issue by jagomf** [gmazzamuto/ng2-google-charts#73]
I have tried `mouseOver` in a GeoChart and it seems to be broken.
Checking the demo files, a [`geoChartData` variable exists](https://github.com/gmazzamuto/ng2-google-charts/blob/55adb381584677c742fc013e969c3d19fb501823/demo/src/app/app.component.ts#L178), but it is not shown in the HTML file.
Error message shown is

> **chart.getChartLayoutInterface is not a function**.

Could you please have a look?

**Comment by gmazzamuto** [comment]
Closed in 99483885dc1f0dc103db491b1e2cd621057cff4e
