### ISSUE TITLE
OrgChart - display Top Node if single row in data

### ISSUE THREAD

**Issue by dlarr** [gmazzamuto/ng2-google-charts#75]
Hello, 

Awsome lib thank you so much.

I am using the orgchart type, and it's working great when there are children nodes, but if the only node to be displayed is the root node, nothing is displayed.

To reproduce this behaviour here are some orgchart data :)
```js
orgChartData2: any =  {
    chartType: 'OrgChart',
    dataTable: [
      [
        {v: 'Mike', f: 'Mike<div style="color:red; font-style:italic">President</div>'}, '', 'The President'
      ]
    ],
    options: { allowHtml: true }
  };
```

Any idea how to display this single root node ?

**EDIT**: I just checked on Google Chart api : it is possible to display 1 node only : https://jsfiddle.net/oj7sdv81/1/

**EDIT2**: Also discovered that Root node is never selectable as other nodes can be :'( 

Thank you very much.
Best regards.

**Comment by gmazzamuto** [comment]
You are missing column names. This works:

```typescript
  public orgChartData: any =  {
    chartType: 'OrgChart',
    dataTable: [
      ['Name',   'Manager', 'Tooltip'],
      [{v: 'Mike', f: 'Mike<div style="color:red; font-style:italic">President</div>'}, '', 'The President'],
    ],
    options: {
      allowHtml: true,
    }
  };
```
