### ISSUE TITLE
Any ideas to load timeline chart using dynamic data from server

### ISSUE THREAD

**Issue by pedrofarbo** [gmazzamuto/ng2-google-charts#78]
Hello, first i want to thank you for this amazing project, this will help me a lot. 

So i have some questions about the implementation of a dynamic data in the timeline chart component,
my server side is in java spring and i'm trying to retrieve the data from him, but i'm stuck in this..

Have any way to make this work? 

Using static data this work good, putting the data directly in the variable.. But if i try to make this data from my server using promises or observables, this return error in the browser console: "Falha no carregamento do <script> com a fonte “https://www.gstatic.com/charts/45.2/i18n/jsapi_compiled_i18n_undefined_module__pt_br.js" and not is load.. 

The funny part is, if i copy and paste the json code from server in the variable transforming in a static json data, this works.. 

Please, if you have any ideas of what is happening in this thing, i will appreciate your help..  

Thanks bro and good job!

**Comment by felipecespedes** [comment]
@pedrofarbo  Btw the error is happening because you are trying to initialize the object that is passed to the `data` attribute and it doesn't have the `chartType` property defined, can you please check that?

**Comment by pedrofarbo** [comment]
@felipecespedes Thank you my brother, i see your example and i guess this will help me..
