### ISSUE TITLE
Define the background color of a geochart

### ISSUE THREAD

**Issue by templth** [gmazzamuto/ng2-google-charts#81]
Hello,

Is it possible to define the background color of a geochart?

Thanks for your help!
Thierry

**Comment by felipecespedes** [comment]
@templth Yes, try the `backgroundColor` option, something like:
```ts
options: {
  title: 'My awesome charts',
  backgroundColor: 'red',
  // other configs ...
}
```

See more details in the official google charts docs https://developers.google.com/chart/interactive/docs/gallery/geochart#configuration-options
