### ISSUE TITLE
Angular 6 & peerDependencies

### ISSUE THREAD

**Issue by jochenjonc** [gmazzamuto/ng2-google-charts#83]
Hi,

I'm already using Angular 6 and when installing ng2-google-charts via npm I get the following warnings:

```
npm WARN ng2-google-charts@3.4.0 requires a peer of @angular/common@^5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-google-charts@3.4.0 requires a peer of @angular/compiler@^5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-google-charts@3.4.0 requires a peer of @angular/core@^5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-google-charts@3.4.0 requires a peer of rxjs@^5.5.6 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-google-charts@3.4.0 requires a peer of typescript@~2.5.3 but none is installed. You must install peer dependencies yourself.
```

Are these really necessary and used by ng2-google-charts? Can I ignore them and even better can they be removed from the package.json so the warnings no longer popup?

I've been testing the charts a little bit and I get no errors.

Regards,

Jochen

**Comment by Myrmex** [comment]
Me too: I could not update Angular using ng update because of these dependencies. Yet, I succeeded to update by uninstalling this package, updating, and reinstalling. Once reinstalled, I ignored the warnings and it seems to work fine.

**Comment by Aaltuj** [comment]
Any updates on this? Is there a plan to update to Angular 6?

**Comment by isametal88** [comment]
Any news? It's annoying to remove and reinstall this package on every update (expecially because it's a configuration issue, the package is working properly even in Angular 7).

**Comment by Metsuryu** [comment]
Looks like this isn't being supported anymore, last commit was on Feb 19, 2018. Maybe someone else should fix it and make a new repo.

**Comment by gmazzamuto** [comment]
@isametal88 I understand, unfortunately I haven't had time to work on this, I'll see if I can fix it in the coming days. Meanwhile I'd be happy to accept a PR if anybody is willing to help.

**Comment by isametal88** [comment]
Hi, 
I tried uninstalling and reinstalling, but the peer dependencies are not updated. Could you please help me?

**Comment by gmazzamuto** [comment]
I haven't published the new package yet, I'll do it soon. In the meantime, if you clone the repo and install it from there it should work.

**Comment by isametal88** [comment]
Hi, no problem, I'll wait for the update. Thank you for your support.
