### ISSUE TITLE
Diff Chart Support

### ISSUE THREAD

**Issue by mjmagin** [gmazzamuto/ng2-google-charts#85]
Hello, just wanted to know if diff charts ( see https://developers.google.com/chart/interactive/docs/gallery/diffchart) are supported ?

Any help much appreciated

**Comment by lianawie** [comment]
Also in need of diff charts please.

**Comment by theunexpected1** [comment]
@lianawie, It does already work, I figured if you give the appropriate role to the columns, they'll appear as diff charts.
`role: 'data'` // current period
`role: 'old-data';` // comparison period

**Comment by lianawie** [comment]
> @lianawie, It does already work, I figured if you give the appropriate role to the columns, they'll appear as diff charts.
> `role: 'data'` // current period
> `role: 'old-data';` // comparison period

Thank you so much

**Comment by simeyla** [comment]
Note: you must put `old-data` role column FIRST

                dataTable.addColumn({ type: lookup[series.type], label: 'Old data', role: 'old-data' });
                dataTable.addColumn({ type: lookup[series.type], label: series.name, role: 'data' });

Although I can't right now see a way to change the label from saying 'Previous Data'. Anyone know how to change that?
