### ISSUE TITLE
Redraw Chart on page load based on screen innerwidth

### ISSUE THREAD

**Issue by gauravshri12** [gmazzamuto/ng2-google-charts#86]
Basically i need to adjust bar chart based on screenwidth for eg- if user opens up the application in Tablet/Ipad or mobile bar chart identify screen width and height and redraw or adjust the same chart in samecontainer.

**On load is not working fine with below code**

@HostListener('load', ['$event']) onPageLoad(event: Event) {
   let selectionMobile = this.lateChartViewMobile.wrapper.visualization.getSelection();
        this.lateChartViewMobile.redraw();
        this.lateChartViewMobile.wrapper.visualization.setSelection(selectionMobile);
  }

**Resize is working fine with below code**

@HostListener('window:resize', ['$event'])
    onWindowResize(event: any) {
        let selection = this.lateChartView.wrapper.visualization.getSelection();
        this.lateChartView.redraw();
        this.lateChartView.wrapper.visualization.setSelection(selection);

        let selectionMobile = this.lateChartViewMobile.wrapper.visualization.getSelection();
        this.lateChartViewMobile.redraw();
        this.lateChartViewMobile.wrapper.visualization.setSelection(selectionMobile);

        let selectionOnTime = this.onTimeChartView.wrapper.visualization.getSelection();
        this.onTimeChartView.redraw();
        this.onTimeChartView.wrapper.visualization.setSelection(selectionOnTime);

        let selectionOnTimeMobile = this.onTimeChartViewMobile.wrapper.visualization.getSelection();
        this.onTimeChartViewMobile.redraw();
        this.onTimeChartViewMobile.wrapper.visualization.setSelection(selectionOnTimeMobile);
        // you can remove two lines that preserve selection if you don't need them
    }

**Comment by sebastianfdez** [comment]
Try this:

In the HTML:
`<google-chart #googleChart [data]="pieChart" [dynamicResize]="true"></google-chart>`

In the .ts
`@ViewChild('googleChart') googleChart: GoogleChartComponent;`
...
`this.googleChart.draw();`
