### ISSUE TITLE
On Page Load chart going out from the box in mobile and tablet view

### ISSUE THREAD

**Issue by gauravshri12** [gmazzamuto/ng2-google-charts#87]
![image](https://user-images.githubusercontent.com/31828662/42015589-f0c2c25a-7a75-11e8-82b6-a37509892b72.png)

Resize is working fine when switch from desktop to tablet view & mobile view but initial page load on tablet and mobile chart not proper.

@HostListener('window:resize', ['$event'])
    onWindowResize(event: any) {
        let selection = this.lateChartView.wrapper.visualization.getSelection();
        this.lateChartView.redraw();
        this.lateChartView.wrapper.visualization.setSelection(selection);

        let selectionMobile = this.lateChartViewMobile.wrapper.visualization.getSelection();
        this.lateChartViewMobile.redraw();
        this.lateChartViewMobile.wrapper.visualization.setSelection(selectionMobile);

        let selectionOnTime = this.onTimeChartView.wrapper.visualization.getSelection();
        this.onTimeChartView.redraw();
        this.onTimeChartView.wrapper.visualization.setSelection(selectionOnTime);

        let selectionOnTimeMobile = this.onTimeChartViewMobile.wrapper.visualization.getSelection();
        this.onTimeChartViewMobile.redraw();
        this.onTimeChartViewMobile.wrapper.visualization.setSelection(selectionOnTimeMobile);
       
    }

**Comment by gmazzamuto** [comment]
Probably it's an issue with the underlying Google Charts library rather than this wrapper. Closing this issue
