### ISSUE TITLE
Add an angular component inside organisation chart box

### ISSUE THREAD

**Issue by oberoivarun** [gmazzamuto/ng2-google-charts#92]
I want to add an angular component html tag inside the Organisation chart box. Is that possible?

`
            [{v: 'Title Of Box', f: '<app-organisation-chart-box></app-organisation-chart-box>'}, '', 'Test']`

Right now it doesn't render anything, probably because its the google api which renders it, and not angular. Could i maybe use a workaround to do this? I want to use a custom component inside the chart box, but i want to use the layout abilities.

**Comment by gmazzamuto** [comment]
Unfortunately this is not possible, it is not compatible with how Angular works
