### ISSUE TITLE
Can I handle reformat datetime show in tooltip ?

### ISSUE THREAD

**Issue by bamossza** [gmazzamuto/ng2-google-charts#93]
![image](https://user-images.githubusercontent.com/12523400/49278749-472b9b00-f4b8-11e8-94cb-9cd6c0e75105.png)

Thanks.

**Comment by gmazzamuto** [comment]
This might help: [https://developers.google.com/chart/interactive/docs/datesandtimes](https://developers.google.com/chart/interactive/docs/datesandtimes)
