### ISSUE TITLE
GeoChart Color Issues

### ISSUE THREAD

**Issue by scottmc0525** [gmazzamuto/ng2-google-charts#94]
@gmazzamuto I am trying to get a map of the US with each state that contains a value in a range. The text should be black and the color should be as specified in bgcolor. It works ok, but the problem is that the chart is always green. Any tips as to what I'm doing wrong, or this a known issue?

`  public geoChartData: any = {
    chartType: "GeoChart",
    apiKey: "blah-blah-blah",
    dataTable: [
      ["State", "Number of Encounters"],
      ["US-AL", 0],
      ["US-AK", 0],
      ["US-AR", 0],
      ["US-AK", 0],
      ["US-AZ", 0],
      ["US-CA", 700],
      ["US-CT", 50],
      ["US-CO", 0],
      ["US-DE", 0],
      ["US-FL", 201],
      ["US-GA", 150],
      ["US-HI", 0],
      ["US-KS", 0],
      ["US-KY", 0],
      ["US-MI", 0],
      ["US-MO", 0],
      ["US-MS", 0],
      ["US-MT", 0],
      ["US-NC", 200],
      ["US-NE", 0],
      ["US-NJ", 300],
      ["US-NM", 0],
      ["US-NY", 205],
      ["US-OR", 0],
      ["US-PA", 0],
      ["US-SC", 100],
      ["US-TX", 101],
      ["US-UT", 0],
      ["US-VA", 0],
      ["US-WA", 0],
      ["US-WV", 0],
      ["US-WY", 0]
    ],
    options: {
      region: "US",
      displayMode: "regions",
      resolution: "provinces"
    },
    formatters: [
      {
        columns: [1],
        type: "ColorFormat",
        options: {
          ranges: [
            {from: 0, to: 50, color: '#000000', bgcolor: '#F8DBE3'},
            {from: 50, to: 100, color: '#000000', bgcolor: '#F1A2AE'},
            {from: 100, to: 200, color: '#000000', bgcolor: '#EC7884'},
            {from: 200, to: 2000, color: '#000000', bgcolor: '#D24F61'}
          ]
        }
      }
    ]
  };`

**Comment by scottmc0525** [comment]
Cancel that - misunderstanding. Doesn't look like an active board anyway. Thanks, though!

**Comment by kbatyrbayev** [comment]
you can do legends: false, and make you custom legend
