### ISSUE TITLE
Dynamically change labels

### ISSUE THREAD

**Issue by jfpicard123** [gmazzamuto/ng2-google-charts#99]
I'm using ngx-translate and would like to translate the labels in the chart onLangChange. Here's my code 

`
    this.translateService.onLangChange.subscribe(async (event: LangChangeEvent) => {
      await this.localize();
    });

...

// Go through the labels and apply translation
  async localize() {
    this.summaryReportLabels = await this.translateService.get(['Reports.SummaryReport']).toPromise();
    let reportData = this.reportData;
    reportData.forEach(d => {
      d.chartData[0][1] = this.summaryReportLabels['Reports.SummaryReport']['Key'];
    });
    this.reportData = reportData;
  }

I know that chartData[0][1] contains the "label" because it is set correctly on first load but not afterwards .. 

Ideas? 
`

**Comment by gmazzamuto** [comment]
Have you tried forcing redraw, as in here?
https://github.com/gmazzamuto/ng2-google-charts/blob/6916d5aaa09d865a64b24a50ae846184e879bb65/demo/src/app/app.component.ts#L389
